name: ci-sonarcloud
on:
  pull_request:
    branches:
      - develop

jobs:
  run_ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@2
      - uses: actions/setup-go@v2
        with:
          go-version: 1.15
      - run: go test -coverprofile=coverage.out
